defmodule Datastar.Conformance.Report do
  @moduledoc """
  Generates the point-in-time conformance record (SDK core spec §18.2 and
  the recorded 2026-09-27 decision): `docs/conformance.md` for humans and
  `docs/conformance.json` for machines, derived ONLY from the pinned
  checkout's golden fixtures, the official runner's log + exit code, and
  the environment. Nothing here is hand-maintained; regeneration happens
  through `scripts/conformance-report` (and every release).

  Result semantics (verified against the v1.0.4 runner): the runner wraps
  `testing.M`, so exit 0 means every golden case passed; on failure it
  emits go-test `--- FAIL: <Test>/<case>` lines for the failing cases.

  Reading the golden fixtures requires the pinned upstream checkout to be
  present at `.conformance/datastar-v1.0.4/`. Run `bash scripts/conformance`
  once to fetch it before running the golden-dir-dependent tests.

  Test-support tooling, not public API.
  """

  @doc "Reads every golden case; raises if the directory is missing or empty."
  def cases(golden_dir) do
    unless File.dir?(golden_dir) do
      raise "golden fixture directory not found: #{golden_dir} — run scripts/conformance once to clone the pinned upstream"
    end

    cases =
      for method <- [:get, :post],
          dir = Path.join(golden_dir, Atom.to_string(method)),
          File.dir?(dir),
          name <- Enum.sort(File.ls!(dir)) do
        %{
          name: name,
          method: method,
          input: dir |> Path.join("#{name}/input.json") |> File.read!() |> JSON.decode!(),
          expected_sse: dir |> Path.join("#{name}/output.txt") |> File.read!()
        }
      end

    if cases == [] do
      raise "no golden cases found under #{golden_dir} — refusing to generate an empty record"
    end

    Enum.sort_by(cases, &{&1.method, &1.name})
  end

  @doc """
  Combines the runner's exit code with its log. Exit 0 ⇒ all cases passed.
  Non-zero ⇒ the `--- FAIL:` cases failed and the rest passed; a non-zero
  exit with NO parsable FAIL lines is an infrastructure error and raises.
  """
  def analyze(_log, 0, _case_names), do: %{result: :pass, failed: []}

  def analyze(log, _nonzero, case_names) do
    failed =
      ~r/^\s*--- FAIL: \w+\/(\S+)/m
      |> Regex.scan(log, capture: :all_but_first)
      |> List.flatten()
      |> Enum.uniq()
      |> Enum.filter(&(&1 in case_names))

    if failed == [] do
      raise "runner failed without naming any golden case — infrastructure error, not drift; refusing to attribute results"
    end

    %{result: :fail, failed: failed}
  end

  @doc "Generates both artifacts. See the moduledoc for required opts."
  def generate(opts) do
    golden = Keyword.fetch!(opts, :golden_dir)
    log = File.read!(Keyword.fetch!(opts, :runner_log))
    exit_code = Keyword.fetch!(opts, :exit_code)
    tag = Keyword.fetch!(opts, :tag)

    cases = cases(golden)
    analysis = analyze(log, exit_code, Enum.map(cases, & &1.name))
    meta = metadata(tag)

    File.write!(Keyword.fetch!(opts, :out_md), render_markdown(meta, cases, analysis))
    File.write!(Keyword.fetch!(opts, :out_json), render_json(meta, cases, analysis))
    :ok
  end

  defp metadata(tag) do
    {commit, 0} = System.cmd("git", ["rev-parse", "--short", "HEAD"])

    %{
      tag: tag,
      library_version: Mix.Project.config()[:version],
      library_commit: String.trim(commit),
      generated_at: DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.to_iso8601(),
      elixir: System.version(),
      otp: List.to_string(:erlang.system_info(:otp_release))
    }
  end

  defp case_result(_case_name, %{result: :pass}), do: :pass

  defp case_result(case_name, %{failed: failed}),
    do: if(case_name in failed, do: :fail, else: :pass)

  defp render_markdown(meta, cases, analysis) do
    {passed, total} = counts(cases, analysis)

    header = markdown_header(meta, analysis, passed, total)
    rows = markdown_rows(cases, analysis)
    details = markdown_details(cases)

    header <> rows <> "\n\n## Case details\n\n" <> details
  end

  defp markdown_header(meta, analysis, passed, total) do
    """
    # Datastar #{meta.tag} conformance record

    > Point-in-time record generated by `mise run conformance-report` — see
    > the Conformance section of the README. Do not edit by hand.

    | | |
    | --- | --- |
    | Upstream tag | `#{meta.tag}` |
    | Library | `datastar_ex #{meta.library_version}` at `#{meta.library_commit}` |
    | Generated | #{meta.generated_at} |
    | Toolchain | Elixir #{meta.elixir} / OTP #{meta.otp} |
    | **Result** | **#{result_banner(analysis, passed, total)}** |

    ## Results

    | Case | Method | Result |
    | --- | --- | --- |
    """
  end

  defp markdown_rows(cases, analysis) do
    Enum.map_join(cases, "\n", fn c ->
      "| #{c.name} | #{c.method |> Atom.to_string() |> String.upcase()} | #{case_result(c.name, analysis)} |"
    end)
  end

  defp markdown_details(cases) do
    Enum.map_join(cases, "\n", fn c ->
      """
      ### #{c.name} (#{c.method |> Atom.to_string() |> String.upcase()})

      Input events:

      ```json
      #{JSON.encode!(c.input)}
      ```

      Expected SSE:

      ```text
      #{String.trim_trailing(c.expected_sse)}
      ```
      """
    end)
  end

  defp render_json(meta, cases, analysis) do
    JSON.encode!(%{
      "datastar_tag" => meta.tag,
      "library_version" => meta.library_version,
      "library_commit" => meta.library_commit,
      "generated_at" => meta.generated_at,
      "toolchain" => %{"elixir" => meta.elixir, "otp" => meta.otp},
      "result" => Atom.to_string(analysis.result),
      "cases" =>
        Enum.map(cases, fn c ->
          %{
            "name" => c.name,
            "method" => Atom.to_string(c.method),
            "result" => c.name |> case_result(analysis) |> Atom.to_string()
          }
        end),
      "known_deviations" => []
    }) <> "\n"
  end

  defp counts(cases, analysis) do
    total = length(cases)
    {total - length(Map.get(analysis, :failed, [])), total}
  end

  defp result_banner(%{result: :pass}, passed, total), do: "PASS (#{passed}/#{total})"
  defp result_banner(_fail, passed, total), do: "FAIL (#{passed}/#{total} passed)"
end
